Makefile: Fjern -pedantic fra CCFLAGS, gcc-4.9.2 klagde
gcc-4.9.2 på Debian 8.8 vil ikke kompilere siden commit 791da6df2c83
("Kompiler medl-add.c med SQLite", 2017-05-15). Det er den beryktede
greia med med «long long» i sqlite3:

  $ gcc --version
  gcc (Debian 4.9.2-10) 4.9.2
  Copyright (C) 2014 Free Software Foundation, Inc.
  $ make
  cc -Wall -Wextra -Werror -O0 -c -g -pedantic dbinit.c
  In file included from medl.h:58:0,
                   from dbinit.c:21:
  sqlite3.h:271:16: error: ISO C90 does not support ‘long long’
 [-Werror=long-long]
     typedef long long int sqlite_int64;
                  ^
  sqlite3.h:272:25: error: ISO C90 does not support ‘long long’
 [-Werror=long-long]
     typedef unsigned long long int sqlite_uint64;
                           ^
  dbinit.c: In function ‘init_db’:
  dbinit.c:101:6: error: string length ‘1136’ is greater than the length
 ‘509’ ISO C90 compilers are required to support
 [-Werror=overlength-strings]
        "COMMIT;\n",
        ^
  cc1: all warnings being treated as errors
  Makefile:19: recipe for target 'dbinit.o' failed
  make: *** [dbinit.o] Error 1
  $

Det har funket fint med gcc-5.4.0 på Linux Mint 18 hele tiden. Oh well.

50a7d1a8-3aa6-11e7-8f2e-db5caa6d21d3

Signed-off-by: Øyvind A. Holm <oyvind@piratpartiet.no>